version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - npm install -g npm@latest
      - npm install --include=dev

  build:
    commands:
      - echo "Building the React app..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Listing contents of dist folder:"
      - ls -al dist || echo "dist folder not found!"
      - pwd

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no
